# Generated by Django 5.2.17 on 2026-08-06 09:27

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_create_homepage"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="closing_heading",
            field=wagtail.fields.RichTextField(
                default="<p>Engineering<br/>complex systems<br/>with <i>controlled<br/>innovation</i>.</p>",
                help_text="Il testo in corsivo viene evidenziato in viola.",
                verbose_name="Titolo",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="contact_email",
            field=models.EmailField(
                default="hello@codever.it", max_length=254, verbose_name="Email"
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="contact_text",
            field=models.CharField(
                default="Talk to our technical team",
                max_length=120,
                verbose_name="Testo di contatto",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="glow_text",
            field=wagtail.fields.RichTextField(
                default="<p>We help companies evolve critical platforms, data flows and digital products by integrating AI in a controlled, deliberate way.<br/>No shortcuts, no black boxes. Every architectural choice is made to ensure stability, scalability and full technical governance over time.</p>",
                verbose_name="Testo",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_badge_text",
            field=models.CharField(
                default="Welcome", max_length=40, verbose_name="Badge"
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_cta_text",
            field=models.CharField(
                default="Explore our systems",
                max_length=60,
                verbose_name="Testo bottone",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_subtitle",
            field=models.TextField(
                default="We design AI-enabled systems that stay controllable,\nstable and scalable over time.",
                help_text="Le interruzioni di riga vengono mantenute.",
                verbose_name="Sottotitolo",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_title_soft",
            field=models.CharField(
                default="It’s engineering.",
                max_length=120,
                verbose_name="Titolo (riga attenuata)",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_title_strong",
            field=models.CharField(
                default="Is not only magic.",
                max_length=120,
                verbose_name="Titolo (riga in evidenza)",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="lets_talk_heading",
            field=models.CharField(
                default="Let’s talk",
                max_length=60,
                verbose_name="Titolo blocco contatto",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="linkedin_url",
            field=models.URLField(
                default="https://www.linkedin.com/company/codever",
                verbose_name="URL LinkedIn",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="products_intro",
            field=models.TextField(
                default="Prodotti e piattaforme progettati per integrarsi in ecosistemi\ncomplessi, rimanendo governabili nel tempo.",
                verbose_name="Introduzione",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="products_title_soft",
            field=models.CharField(
                default="built for real systems",
                max_length=120,
                verbose_name="Titolo (riga attenuata)",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="products_title_strong",
            field=models.CharField(
                default="AI products,",
                max_length=120,
                verbose_name="Titolo (riga in evidenza)",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="services_intro",
            field=models.TextField(
                default="I nostri prodotti nascono da competenze ingegneristiche\nprofonde e da un approccio strutturato alla complessità.",
                verbose_name="Introduzione",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="services_title_soft",
            field=models.CharField(
                default="behind the products",
                max_length=120,
                verbose_name="Titolo (riga attenuata)",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="services_title_strong",
            field=models.CharField(
                default="Engineering excellence",
                max_length=120,
                verbose_name="Titolo (riga in evidenza)",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="statement",
            field=wagtail.fields.RichTextField(
                default="<p>Codever designs and governs <i>complex digital systems</i>, where AI meets engineering discipline and long‑term reliability.</p>",
                help_text="Il testo in corsivo viene evidenziato in viola.",
                verbose_name="Statement",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="styling_focus_heading",
            field=models.CharField(
                default="Focus", max_length=40, verbose_name="Titolo elenco focus"
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="styling_focus_items",
            field=models.TextField(
                default="Virtual Try‑On\nGenerazione controllata di asset\nIntegrazione con sistemi retail esistenti",
                help_text="Una voce per riga.",
                verbose_name="Voci focus",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="styling_portrait",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Ritratto",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="styling_portrait_alt",
            field=models.CharField(
                default="Fashion portrait generated with the Styling Suite",
                max_length=200,
                verbose_name="Testo alternativo ritratto",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="styling_sub",
            field=models.TextField(
                default="Esperienze AI avanzate pensate per ambienti retail reali, dove performance, qualità visiva e integrazione contano più dell’effetto wow.",
                verbose_name="Sottotitolo",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="styling_title_soft",
            field=models.CharField(
                default="for Fashion",
                max_length=120,
                verbose_name="Titolo (riga attenuata)",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="styling_title_strong",
            field=models.TextField(
                default="Styling Suite On\n& Generative AI",
                help_text="Una riga del titolo per ogni riga di testo.",
                verbose_name="Titolo (righe in evidenza)",
            ),
        ),
        migrations.CreateModel(
            name="ClosingInfoBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("heading", models.CharField(max_length=60, verbose_name="Titolo")),
                (
                    "body",
                    models.TextField(
                        help_text="Le interruzioni di riga vengono mantenute.",
                        verbose_name="Testo",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="closing_info_blocks",
                        to="home.homepage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductShot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Testo alternativo"
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Immagine",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_shots",
                        to="home.homepage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ServiceCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "title",
                    models.TextField(
                        help_text="Le interruzioni di riga vengono mantenute.",
                        verbose_name="Titolo",
                    ),
                ),
                (
                    "footer_text",
                    models.CharField(
                        max_length=200, verbose_name="Testo a piè di card"
                    ),
                ),
                (
                    "icon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Icona",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_cards",
                        to="home.homepage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
